import { NAMED_RULES } from "./lib/rules.ts";
/**
 * Contains core logic behind the automata, seperated from any interface that controls it
 * no reliance on DOM, could be turned into terminal utility.
 */

/**
 * Main datastructure for component, anything that can effect the next state calculation of the grid
 * should be in this object.
 */
const mouseModes: ("observe" | "randomize" | "kill" | "set")[] = [
  "observe",
  "randomize",
  "kill",
  "set",
];
type Activation = "sigmoid" | "power" | "gaussian" | "will";
interface Command {
  command: string;
  [key: string]: any;
}
export interface Grid {
  width: number;
  height: number;
  cells: Float64Array;

  /** properties for shaping probability */
  alpha: number;
  beta: number;
  /**
   * how much of the function result to apply to the cell state per tick
   * classic conways only runs at 1
   */
  changeRate: number;

  /**
   * If specified a phase diagram is generated by ignoring alpha and beta and creating them based
   * on supplied range interpolated of x and y
   */
  phaseDiagram?: [number, number];

  /** The activation function to use. i.e. gaussian or power transform */
  activation: Activation;

  /** Eventual refactor when UX pattern resolved */
  mouseMode: "observe" | "randomize" | "kill" | "set";
  brushSize: number;
  brushProb: number;
  mouseIsDown: boolean;
  mousePosition: [number, number];
  position: number;
  playing: boolean;
}

export class LifeLike {
  grid: Grid;

  constructor(grid?: Partial<Grid>) {
    this.grid = LifeLike.createGrid(grid);
    return;
  }

  /**
   * Create a new grid assuming defaults but accepting any partial Grid properties
   */
  static createGrid(initial: Partial<Grid> = { width: 100, height: 100 }): Grid {
    const width = initial.width ?? 100;
    const height = initial.height ?? 100;
    const grid: Grid = {
      mouseMode: "randomize",
      brushProb: .5,
      brushSize: 10,
      position: 0,
      mouseIsDown: false,
      mousePosition: [0, 0],
      width,
      height,
      // New bytes are initialized to 0
      cells: new Float64Array(new ArrayBuffer(8 * width * height)),
      playing: false,
      alpha: 1,
      beta: .5,
      changeRate: 5,
      activation: "gaussian",
    };
    Object.assign(grid, initial);
    return grid;
  }
  /**
   * This function is intended to expose grid operations that can be
   * recorded in a file as JSON or JSONL in the format `{ command: "foo", args: "bar" }`
   *
   * Currently it also contains UI state, which should be simplified to a more generic interface. In
   * theory this allows UI recordings to be replayed via the terminal command. not implemented.
   */
  stdin(command: Command) {
    switch (command.command) {
      case "reset-random":
        this.resetRandom();
        return;
      case "make-symmetric":
        this.makeSymmetric();
        return;
      case "increase-prob-m":
        this.grid.alpha += .01;
        return;
      case "decrease-prob-m":
        this.grid.alpha -= .01;
        return;
      case "increase-prob-x":
        this.grid.beta += .01;
        return;
      case "decrease-prob-x":
        this.grid.beta -= .01;
        return;
      case "increase-prob-y":
        this.grid.changeRate += .01;
        return;
      case "decrease-prob-y":
        this.grid.changeRate -= .01;
        return;
      case "mouse-mode":
        const currentIndex = mouseModes.indexOf(this.grid.mouseMode);
        const nextIndex = (currentIndex + 1) % mouseModes.length;
        this.grid.mouseMode = mouseModes[nextIndex];
        return;
      case "increase-brush-prob":
        this.grid.brushProb += .01;
        return;
      case "decrease-brush-prob":
        this.grid.brushProb -= .01;
        return;
      case "increase-brush":
        this.grid.brushSize += 1;
        return;
      case "decrease-brush":
        this.grid.brushSize -= 1;
        if (this.grid.brushSize < 1) this.grid.brushSize = 1;
        return;
      case "mousedown":
        this.grid.mouseIsDown = true;
        return;
      case "mouseup":
        this.grid.mouseIsDown = false;
        return;
      case "mousemove":
        this.grid.mousePosition = command.pos;
        return;
      case "tick":
        this.tick();
        return;
      case "play-pause":
        this.grid.playing = !this.grid.playing;
        if (this.grid.playing) this.play();
        return;
      case "move-right":
        this.grid.position++;
        return;
      case "move-left":
        this.grid.position--;
        return;
      case "move-down":
        this.grid.position += this.grid.width;
        return;
      case "move-up":
        this.grid.position -= this.grid.width;
        return;
      case "toggle-cell":
        this.grid.cells[this.grid.position] = Number(!this.grid.cells[this.grid.position]);
        return;
      case "random-cell":
        this.grid.cells[this.grid.position] = Math.random();
        return;
      case "reset":
        this.grid.cells = new Float64Array(new ArrayBuffer(8 * this.grid.width * this.grid.height));
        return;
      case "goto-start":
        this.grid.position = 0;
        return;
      case "goto-end":
        this.grid.position = (this.grid.width * this.grid.height) - 1;
        return;
    }
  }

  /**
   * Calculate the next state of the grid
   */
  tick() {
    this.grid.cells = LifeLike.getNextState(this.grid);
  }

  /**
   * Compute the next state of the grid
   */
  static getNextState(grid: Grid, phaseDiagram = true, wrap = false): Float64Array {
    /** Create a new 1D array of 8 bit floats that represent grid state */
    const nextState = new Float64Array(new ArrayBuffer(8 * grid.width * grid.height));
    for (let position = 0; position < grid.cells.length; position++) {
      // Output state to be modified via rules, shaping functions, and rate of change
      let state = 0;
      // Sort is needed for determinism since floating point arithmatic is not associative
      const neighbors = LifeLike.getNeighborhood(position, grid, wrap).sort();
      // Compute the odds that are used for applying conways rules or other life-like rules.
      const odds = LifeLike.computeNeighborTotalOddsDC(neighbors);

      /**
       * Apply the life-like rules. Since the system is probabilistic, multiple sets of rules
       * can be combined. A simulation could be 75% conways and 25% diomoeba
       *
       * named rule list: dayNight, diomoeba, anneal
       */
      state = (
        2 * NAMED_RULES.conway(grid, position, odds) +
        NAMED_RULES.diomoeba(grid, position, odds)
      ) / 3;

      // Floating point stuff
      state = Math.min(1, Math.max(0, state));

      /**
       * Apply the shaping function to get interesting behaviour out of the rules, if creating
       * a phase diagram these vary based on x/y position, otherwise use grid state properties
       */
      if (!phaseDiagram) {
        state = LifeLike.sigmoid(state, grid.alpha, grid.beta);
      } else {
        const x = position % grid.width + 1;
        const y = (position - x) / grid.width;

        /** Hard coded values found through experimentation */
        /* Use on gaussian
        const a = LifeLike.linearInterpolate(grid.width, x, -.5, .5);
        const b = LifeLike.linearInterpolate(grid.height, y, -.5, .5);
        */

        /**
        * power transform
        const a = LifeLike.linearInterpolate(grid.width, x, .001, 6);
        const b = LifeLike.linearInterpolate(grid.height, y, .25, .6);
       */

        const a = LifeLike.linearInterpolate(grid.width, x, 6, 8);
        const b = LifeLike.linearInterpolate(grid.height, y, .35, .4);
        state = LifeLike.powerTransform(state, a, b);
        //state = LifeLike.sigmoid(state, a, b);
        //state = LifeLike.gaussian(state, a, b);
        //
      }

      /**
       * Apply the change rate of the grid. Undecided if I should hardcode 0 and 1 to preserve
       * conway behaviour on integer state values on all settings
       */
      const change = state - grid.cells[position];
      state = grid.cells[position] + (change / grid.changeRate);

      // Set next state value
      nextState[position] = state;
    }

    return nextState;
  }

  static linearInterpolate(size: number, i: number, min: number, max: number): number {
    return min + (max - min) * (i / size);
  }

  /**
   * Resets the grid to have cell states to be randomized.
   *
   * density is how likely a cell is to be randomized.
   *
   * min and max should be between 0 and 1
   */
  resetRandom(density: number = .1, min: number = 0, max: number = 1) {
    for (let position = 0; position < this.grid.cells.length; position++) {
      const x = position % this.grid.width;
      const y = (position - x) / this.grid.width;
      const density = LifeLike.linearInterpolate(this.grid.width, x, 0, 1);
      const min = LifeLike.linearInterpolate(this.grid.height, y, 0, 1);
      if (Math.random() > density) {
        const value = Math.random() * (1 - min) + min;
        this.grid.cells[position] = value;
      } else {
        this.grid.cells[position] = 0;
      }
    }
  }

  /** Mirrors the top left quadrant to the other 3 quadrants */
  makeSymmetric() {
    const newCells = new Float64Array(new ArrayBuffer(8 * this.grid.width * this.grid.height));
    for (let position = 0; position < this.grid.cells.length; position++) {
      const x = position % this.grid.width;
      const y = (position - x) / this.grid.width;
      //** This is top left quadrant, which gets mirrored to other quadrants */
      if (x < this.grid.width / 2 && y < this.grid.height / 2) {
        const xOffset = this.grid.width - (2 * x) - 1;
        const yOffset = (this.grid.height - 1) - (2 * y);

        newCells[position] = this.grid.cells[position];
        newCells[position + xOffset] = this.grid.cells[position];
        newCells[position + xOffset + yOffset * this.grid.width] = this.grid.cells[position];
        newCells[position + yOffset * this.grid.width] = this.grid.cells[position];
      }
    }
    this.grid.cells = newCells;
  }

  /**
   * Get's the neighborhood for the cell at specified position. If the position is on the edge of
   * the grid, it's neighbor is the opposite edge.
   * @TODO: optimize
   */
  static getNeighborhood(position: number, grid: Grid, wrap = true): number[] {
    const x = position % grid.width;
    const y = (position - x) / grid.width;
    // return value is a lenght 8 array
    // 0 1 2
    // 3 C 4
    // 5 6 7
    //const neighbors = new Int16Array(8);
    const neighbors = [];

    // return value of neighbors
    const n = new Array(8);
    /** Set the position for each neighor */
    neighbors[0] = position - grid.width - 1;
    neighbors[1] = position - grid.width;
    neighbors[2] = position - grid.width + 1;
    neighbors[3] = position - 1;
    neighbors[4] = position + 1;
    neighbors[5] = position + grid.width - 1;
    neighbors[6] = position + grid.width;
    neighbors[7] = position + grid.width + 1;

    // Will read garbage on edge cases, but gets reset to correct value below

    for (let i = 0; i < neighbors.length; i++) n[i] = grid.cells[neighbors[i]];
    if (wrap) {
      /**
       * By default, wrap to the other side of the grid when reaching an edge
       */
      if (position < grid.width) {
        // Position is on top side
        neighbors[0] += grid.cells.length;
        neighbors[1] += grid.cells.length;
        neighbors[2] += grid.cells.length;
      } else if (position >= grid.width * (grid.height - 1)) {
        //position is on bottom side
        neighbors[5] -= grid.cells.length;
        neighbors[6] -= grid.cells.length;
        neighbors[7] -= grid.cells.length;
      }

      if (position % grid.width === 0) {
        // Position is left side
        neighbors[0] += grid.width;
        neighbors[3] += grid.width;
        neighbors[5] += grid.width;
      } else if ((position + 1) % grid.width === 0) {
        // Position is right side
        neighbors[2] -= grid.width;
        neighbors[4] -= grid.width;
        neighbors[7] -= grid.width;
      }
    } else {
      /**
       * If wrap is false, then treat the edges as dead cells.
       */
      if (y === 0) n[0] = n[1] = n[2] = 0;
      if (y === grid.height - 1) n[5] = n[6] = n[7] = 0;
      if (x === 0) n[0] = n[3] = n[5] = 0;
      if (x === grid.width - 1) n[2] = n[4] = n[7] = 0;
    }
    return n;
  }

  /**
   * Below are various functions for adjusting the shape of the probability that comes out of the
   * cell rules.
   */

  // Same type of activation function used for lenia. A bump shape.
  //     .-.
  //    /   \
  // __/     \__
  static gaussian(x: number, center: number, width: number): number {
    const z = (x - center) / width;
    return Math.exp(-0.5 * z * z);
  }

  /**
   * characteristic s shaped function
   * returns 0 < v < 1, never a 0 or 1
   * arbitrary real input
   */
  static sigmoid(value: number, gamma: number, offset: number): number {
    return 1 / (1 + Math.pow(Math.E, gamma * (-value + offset)));
  }

  /**
   * Similar S shape to a sigmoid, but f(0) = 0 and f(1) = 1
   * Input must be 0-1
   */
  static powerTransform(prob: number, alpha: number, offset: number): number {
    const t = Math.pow(offset, alpha);
    const oneMinusT = Math.pow(1 - offset, alpha);
    const num = Math.pow(prob, alpha) * oneMinusT;
    return num / (num + Math.pow(1 - prob, alpha) * t);
  }

  /**
   * My hacky function that just takes a slope, inverts it around a threshold, and adds a constant
   * value. Even after adding various better functions this continued to produce good patterns.
   *
   * kinda like a sigmoid in general shape.
   */
  static shapeProbability(state: number, m: number, x: number, y: number): number {
    if (state >= 1) return 1;
    if (state <= 0) return 0;
    /** Apply my hacky function */

    if (state < x) {
      state = state / m + y;
    } else {
      state = 1 - ((1 - state) / m) + y;
    }
    /* */
    if (state >= 1) return 1;
    if (state <= 0) return 0;
    return state;
  }

  /**
   * computeNeighborTotalOdds and computeNeighborStateOdds are a brute force way of computing the
   * probabilities of every neighor state for a cell. No longer used since the direct convolution
   * method was added, but left for potential use as tests.
   *
   * Given the possibility of each state, output the possibilites of a certain number of neighbors
   * being alive.
   */
  static computeNeighborTotalOdds(odds: number[]) {
    const res: number[] = [0, 0, 0, 0, 0, 0, 0, 0, 0];
    for (let i = 0; i < odds.length; i++) {
      //bit count is the number of alive neighbors
      let numNeighbors = LifeLike.bitCount(i);
      res[numNeighbors] += odds[i];
    }
    return res;
  }

  /**
   * Iterates over all possible states that neighbors could be in and calculates the chance of each
   * one being true.
   * e.g.
   * prob(00110101) = p(neighor 0 dead) * p(neighbor 1 dead) * prob(neighor 2 alive)...
   */
  static computeNeighborStateOdds(neighbors: number[]): number[] {
    /** Odds for each state if the neighbors */
    const odds: number[] = [];
    /**
     * Iterate over every possible state that a neighbor could be in
     */
    for (let i = 0; i < 256; i++) {
      let prob = 1;
      /**
       * Iterate over each neighbor and compute the odds that this neighbor is in
       * this state
       */
      for (let j = 0; j < 8; j++) {
        const neighbor = neighbors[j];
        /** If this neighbor (j) is alive in this state (i), apply the prob */
        /** 2 ** j === 2^j, or the j'th bit turned on */
        if ((2 ** j) & i) {
          prob = prob * neighbor;
        } else {
          prob = prob * (1 - neighbor);
        }
        /** No need to continue computing odds if state is impossible */
        if (prob === 0) break;
      }
      odds.push(prob);
    }

    return odds;
  }

  /**
   * Implementation of the direct convolution method on wikiepedia page
   *
   * Sat Apr 25 05:59:37 PM EDT 2026
   * https://en.wikipedia.org/wiki/Poisson_binomial_distribution
   *
   * and tested manually against brute force
   */
  static computeNeighborTotalOddsDC(neighbors: number[]): number[] {
    const n = neighbors.length;
    const res: number[] = new Array(n + 1).fill(0);
    res[0] = 1;
    for (let i = 0; i < n; i++) {
      const p = neighbors[i];
      const q = 1 - p;
      for (let k = i + 1; k > 0; k--) {
        res[k] = res[k] * q + res[k - 1] * p;
      }
      res[0] = res[0] * q;
    }
    return res;
  }

  // Neighbor state is a number, where each bit on is that neighbor being alive or
  // dead
  static bitCount(n: number) {
    n = n - ((n >> 1) & 0x55555555);
    n = (n & 0x33333333) + ((n >> 2) & 0x33333333);
    return ((n + (n >> 4) & 0xF0F0F0F) * 0x1010101) >> 24;
  }

  /**
   * @TODO Sat Apr 25 05:41:20 PM EDT 2026
   *
   * Eventuallly I need to do a major refactor of UX, once I figure out what the actual flow of the
   * UX is and how unified it will be across web component and terminal utility.
   *
   * For now, I've moved the major functions that will need to be addressed at some point.
   */

  /**
   * Currently used by web component
   *
   * @TODO Sat Apr 25 05:38:21 PM EDT 2026
   * Need to decidie if terminal utility would use play. I'm leaning towards yes but otherwise could
   * be removed. Needs a general refactor/rewrite.
   */
  play() {
    const now = Date.now();
    // Update from user input, regardless if paused or not
    if (this.grid.mouseIsDown) {
      const b = this.grid.brushSize;
      const [x, y] = this.grid.mousePosition;
      for (let i = x - b; i < x + b; i++) {
        if (x < 0 || x > this.grid.width) continue;
        for (let j = y - b; j < y + b; j++) {
          if (y < 0 || y > this.grid.width) continue;
          const dist = Math.sqrt((i - x) ** 2 + (j - y) ** 2) + 1;
          if (dist > b) continue;
          // Depending on the mouse mode, modify the state
          const pos = i + j * this.grid.width;
          switch (this.grid.mouseMode) {
            case "observe":
              if (this.grid.cells[pos] < 0) console.log(this.grid.cells[pos]);
              if (this.grid.cells[pos] > Math.random()) {
                this.grid.cells[pos] = 1;
              } else {
                this.grid.cells[pos] = 0;
              }
              break;
            case "randomize":
              this.grid.cells[pos] = Math.random();
              break;
            case "kill":
              this.grid.cells[pos] = 0;
              break;
            case "set":
              this.grid.cells[pos] = this.grid.brushProb;
              break;
          }
        }
      }
    }

    const time = Date.now() - now;
    setTimeout(() => this.play(), 50);
    return false;
  }
}
