type Shape = "moore" | "vonNeumann" | "circular";
import { NAMED_RULES } from "./lib/rules.ts";
import { ShaperName, Shapers } from "./shapers.ts";
// ColorMap is a global singleton that contains the current theme.
import { ColorMap, PaletteName, Themes } from "./lib/ColorMap.ts";

/**
 * Contains core logic behind the automata, seperated from any interface that controls it
 * no reliance on DOM, could be turned into terminal utility.
 */

interface Command {
  command: string;
  [key: string]: any;
}
export interface Grid {
  mode: "PhaseDiagram" | "Fixed";
  width: number;
  height: number;
  cells: Float64Array;

  /** properties for shaping probability */
  alpha: number;
  beta: number;
  /**
   * how much of the function result to apply to the cell state per tick
   * classic conways only runs at 1
   */
  changeRate: number;

  /**
   * If specified a phase diagram is generated by ignoring alpha and beta and creating them based
   * on supplied range interpolated of x and y
   */
  phaseDiagram: {
    alpha: [number, number];
    beta: [number, number];
  };

  /** The activation function to use. i.e. gaussian or power transform */
  activation: ShaperName;

  playing: boolean;
  theme: PaletteName;
}

export class LifeLike {
  grid: Grid;

  constructor(grid?: Partial<Grid>) {
    this.grid = LifeLike.createGrid(grid);
    return;
  }

  /**
   * Create a new grid assuming defaults but accepting any partial Grid properties
   */
  static createGrid(initial: Partial<Grid> = {}): Grid {
    const grid: Grid = {
      width: initial.width ? initial.width : 100,
      height: initial.height ? initial.height : 100,
      cells: new Float64Array(),
      mode: "PhaseDiagram",
      // New bytes are initialized to 0
      playing: false,
      alpha: 1,
      beta: .5,
      changeRate: 1,
      activation: "gaussian",
      phaseDiagram: Shapers["gaussian"].diagram,
      theme: "viridis",
    };
    Object.assign(grid, initial);
    /**
     * If the initial grid didn't specify its cells or phase diagram, update it
     * based on what is specified.
     */
    if (!initial.cells) grid.cells = new Float64Array(8 * grid.width * grid.height);
    if (!initial.phaseDiagram) grid.phaseDiagram = Shapers[grid.activation].diagram;

    ColorMap.load(grid.theme);
    return grid;
  }
  /**
   * This function is intended to expose grid operations that can be
   * recorded in a file as JSON or JSONL in the format `{ command: "foo", args: "bar" }`
   *
   * In theory allows for replay of commands via JSONL
   */
  stdin(command: Command) {
    if (Object.hasOwn(Controls, command.command)) {
      //@ts-ignore
      Controls[command.command as ControlName](this.grid, command.args);
    }
    return;
  }

  /**
   * Compute the next state of the grid
   */
  static getNextState(grid: Grid): Float64Array {
    const wrap = grid.mode === "Fixed";
    /** Create a new 1D array of 8 bit floats that represent grid state */
    const nextState = new Float64Array(new ArrayBuffer(8 * grid.width * grid.height));

    for (let position = 0; position < grid.cells.length; position++) {
      let state = 0; // State is iteretively modified by rules & activation function
      // Sort is needed for determinism since floating point arithmatic is not associative
      //const neighbors = LifeLike.getNeighborhood(position, grid, wrap).sort();
      const neighbors = LifeLike.getLargerNeighborhood(position, grid, 5).sort();

      // Comput PMF, result is an array wher pmf[i] = odds of i living neighbors
      const odds = LifeLike.computeNeighborTotalOddsDC(neighbors);

      // Apply rules to PMF
      //state = NAMED_RULES.conway(grid, position, odds);
      state = NAMED_RULES.ltl(grid, position, odds);
      // Get the activation function and alpha/beta params
      const [alpha, beta] = LifeLike.getAlphaBeta(grid, position);
      const activation = Shapers[grid.activation].fn;

      // apply the activation function
      state = activation(state, alpha, beta);
      // smooth the time step
      state = grid.cells[position] + ((state - grid.cells[position]) / grid.changeRate);
      nextState[position] = isNaN(state) ? 0 : state;

      // Set next state value
      /** @TODO
       * This was a hacky test of seeing interpolating between life-like rules. it actually works
       * and produces output without the need for an activation function. Worth refactoring at
       * some point to do a better job of exploring the compbinations
      if (grid.mode === "Fixed") {
        const a = grid.alpha;
        const b = grid.beta;
        state = (a * NAMED_RULES.diomoeba(grid, position, odds) +
          b * NAMED_RULES.anneal(grid, position, odds)) / (a + b);
      } else {
        const x = position % grid.width + 1;
        const y = (position - x) / grid.width;
        const [minA, maxA] = grid.phaseDiagram.alpha;
        const [minB, maxB] = grid.phaseDiagram.beta;
        const a = LifeLike.linearInterpolate(grid.width, x, minA, maxA);
        const b = LifeLike.linearInterpolate(grid.height, y, minB, maxB);
        state = (a * NAMED_RULES.diomoeba(grid, position, odds) +
          b * NAMED_RULES.anneal(grid, position, odds)) / (a + b);
      }
       */
    }

    return nextState;
  }

  static getAlphaBeta(grid: Grid, position: number): [number, number] {
    if (grid.mode === "Fixed") {
      return [grid.alpha, grid.beta];
    } else {
      const x = position % grid.width + 1;
      const y = (position - x) / grid.width;
      const [minA, maxA] = grid.phaseDiagram.alpha;
      const [minB, maxB] = grid.phaseDiagram.beta;
      const a = LifeLike.linearInterpolate(grid.width, x, minA, maxA);
      const b = LifeLike.linearInterpolate(grid.height, y, minB, maxB);
      return [a, b];
    }
  }

  static linearInterpolate(size: number, i: number, min: number, max: number): number {
    return min + (max - min) * (i / size);
  }

  /**
   * Get's the neighborhood for the cell at specified position. If the position is on the edge of
   * the grid, it's neighbor is the opposite edge.
   * @TODO: optimize
   */
  static getNeighborhood(position: number, grid: Grid, wrap = true): number[] {
    const x = position % grid.width;
    const y = (position - x) / grid.width;
    // return value is a lenght 8 array
    // 0 1 2
    // 3 C 4
    // 5 6 7
    //const neighbors = new Int16Array(8);
    const neighbors = [];

    // return value of neighbors
    const n = new Array(8);
    /** Set the position for each neighor */
    neighbors[0] = position - grid.width - 1;
    neighbors[1] = position - grid.width;
    neighbors[2] = position - grid.width + 1;
    neighbors[3] = position - 1;
    neighbors[4] = position + 1;
    neighbors[5] = position + grid.width - 1;
    neighbors[6] = position + grid.width;
    neighbors[7] = position + grid.width + 1;

    // Will read garbage on edge cases, but gets reset to correct value below

    if (wrap) {
      /**
       * By default, wrap to the other side of the grid when reaching an edge
       */
      if (position < grid.width) {
        // Position is on top side
        neighbors[0] += grid.cells.length;
        neighbors[1] += grid.cells.length;
        neighbors[2] += grid.cells.length;
      } else if (position >= grid.width * (grid.height - 1)) {
        //position is on bottom side
        neighbors[5] -= grid.cells.length;
        neighbors[6] -= grid.cells.length;
        neighbors[7] -= grid.cells.length;
      }

      if (position % grid.width === 0) {
        // Position is left side
        neighbors[0] += grid.width;
        neighbors[3] += grid.width;
        neighbors[5] += grid.width;
      } else if ((position + 1) % grid.width === 0) {
        // Position is right side
        neighbors[2] -= grid.width;
        neighbors[4] -= grid.width;
        neighbors[7] -= grid.width;
      }
      for (let i = 0; i < neighbors.length; i++) n[i] = grid.cells[neighbors[i]];
    } else {
      for (let i = 0; i < neighbors.length; i++) n[i] = grid.cells[neighbors[i]];
      /**
       * If wrap is false, then treat the edges as dead cells.
       */
      if (y === 0) n[0] = n[1] = n[2] = 0;
      if (y === grid.height - 1) n[5] = n[6] = n[7] = 0;
      if (x === 0) n[0] = n[3] = n[5] = 0;
      if (x === grid.width - 1) n[2] = n[4] = n[7] = 0;
    }
    return n;
  }

  static getLargerNeighborhood(
    position: number,
    grid: Grid,
    R: number,
    shape: Shape = "circular",
  ): number[] {
    const x = position % grid.width;
    const y = (position - x) / grid.width;
    const neighbors: number[] = [];

    for (let dy = -R; dy <= R; dy++) {
      for (let dx = -R; dx <= R; dx++) {
        if (dx === 0 && dy === 0) continue; // exclude center

        // Shape mask — pick which cells count as "in the neighborhood"
        let inShape: boolean;
        switch (shape) {
          case "moore":
            inShape = true;
            break; // full square
          case "vonNeumann":
            inShape = Math.abs(dx) + Math.abs(dy) <= R;
            break; // diamond
          case "circular":
            inShape = dx * dx + dy * dy <= R * R;
            break; // disc
        }
        if (!inShape) continue;

        const nx = x + dx;
        const ny = y + dy;
        neighbors.push(
          nx < 0 || nx >= grid.width || ny < 0 || ny >= grid.height
            ? 0
            : grid.cells[ny * grid.width + nx],
        );
      }
    }
    return neighbors;
  }

  /**
   * computeNeighborTotalOdds and computeNeighborStateOdds are a brute force way of computing the
   * probabilities of every neighor state for a cell. No longer used since the direct convolution
   * method was added, but left for potential use as tests.
   *
   * Given the possibility of each state, output the possibilites of a certain number of neighbors
   * being alive.
   */
  static computeNeighborTotalOdds(odds: number[]) {
    const res: number[] = [0, 0, 0, 0, 0, 0, 0, 0, 0];
    for (let i = 0; i < odds.length; i++) {
      //bit count is the number of alive neighbors
      let numNeighbors = LifeLike.bitCount(i);
      res[numNeighbors] += odds[i];
    }
    return res;
  }

  /**
   * Iterates over all possible states that neighbors could be in and calculates the chance of each
   * one being true.
   * e.g.
   * prob(00110101) = p(neighor 0 dead) * p(neighbor 1 dead) * prob(neighor 2 alive)...
   */
  static computeNeighborStateOdds(neighbors: number[]): number[] {
    /** Odds for each state if the neighbors */
    const odds: number[] = [];
    /**
     * Iterate over every possible state that a neighbor could be in
     */
    for (let i = 0; i < 256; i++) {
      let prob = 1;
      /**
       * Iterate over each neighbor and compute the odds that this neighbor is in
       * this state
       */
      for (let j = 0; j < 8; j++) {
        const neighbor = neighbors[j];
        /** If this neighbor (j) is alive in this state (i), apply the prob */
        /** 2 ** j === 2^j, or the j'th bit turned on */
        if ((2 ** j) & i) {
          prob = prob * neighbor;
        } else {
          prob = prob * (1 - neighbor);
        }
        /** No need to continue computing odds if state is impossible */
        if (prob === 0) break;
      }
      odds.push(prob);
    }

    return odds;
  }

  /**
   * Implementation of the direct convolution method on wikiepedia page
   *
   * Sat Apr 25 05:59:37 PM EDT 2026
   * https://en.wikipedia.org/wiki/Poisson_binomial_distribution
   *
   * and tested manually against brute force
   */
  static computeNeighborTotalOddsDC(neighbors: number[]): number[] {
    const n = neighbors.length;
    const res: number[] = new Array(n + 1).fill(0);
    res[0] = 1;
    for (let i = 0; i < n; i++) {
      const p = neighbors[i];
      const q = 1 - p;
      for (let k = i + 1; k > 0; k--) {
        res[k] = res[k] * q + res[k - 1] * p;
      }
      res[0] = res[0] * q;
    }
    return res;
  }

  // Neighbor state is a number, where each bit on is that neighbor being alive or
  // dead
  static bitCount(n: number) {
    n = n - ((n >> 1) & 0x55555555);
    n = (n & 0x33333333) + ((n >> 2) & 0x33333333);
    return ((n + (n >> 4) & 0xF0F0F0F) * 0x1010101) >> 24;
  }
}

type Control = (grid: Grid, args: any) => void;
/**
 * Controls is a 1-1 mapping of stdin command string to synchronous functions that manipulate Grid
 * state
 */
const Controls = {
  /** advances the grid a single tick */
  "tick"(grid) {
    grid.cells = LifeLike.getNextState(grid);
  },
  /** Toggles between PhaseDiagram mode and FixedMode */
  "toggle-mode"(grid) {
    grid.mode = grid.mode === "PhaseDiagram" ? "Fixed" : "PhaseDiagram";
  },
  /**
   * Resets the grid, interpolating over width & height to set density and
   * magnitude of life cells
   */
  "reset-random"(grid) {
    const densityRange = [0, 1];
    const valueRange = [0, .5];

    for (let position = 0; position < grid.cells.length; position++) {
      const x = position % grid.width;
      const y = (position - x) / grid.width;
      const density = LifeLike.linearInterpolate(grid.width, x, densityRange[0], densityRange[1]);
      const min = LifeLike.linearInterpolate(grid.height, y, valueRange[0], valueRange[1]);
      if (Math.random() > density) {
        grid.cells[position] = Math.random() * (1 - min) + min;
      } else {
        grid.cells[position] = 0;
      }
    }
  },
  /**
   * Mirrors the top left quadrant to all other quadrants. mostly for the purpose of good visaul
   * patterns
   */
  "make-symmetric"(grid) {
    const newCells = new Float64Array(new ArrayBuffer(8 * grid.width * grid.height));
    for (let position = 0; position < grid.cells.length; position++) {
      const x = position % grid.width;
      const y = (position - x) / grid.width;
      //** This is top left quadrant, which gets mirrored to other quadrants */
      if (x < grid.width / 2 && y < grid.height / 2) {
        const xOffset = grid.width - (2 * x) - 1;
        const yOffset = (grid.height - 1) - (2 * y);

        newCells[position] = grid.cells[position];
        newCells[position + xOffset] = grid.cells[position];
        newCells[position + xOffset + yOffset * grid.width] = grid.cells[position];
        newCells[position + yOffset * grid.width] = grid.cells[position];
      }
    }
    grid.cells = newCells;
  },
  /**
   * 0s out the entire grid
   */
  "reset"(grid) {
    grid.cells = new Float64Array(new ArrayBuffer(8 * grid.width * grid.height));
  },

  "load-state"(grid, state: Partial<Grid>) {
    Object.assign(grid, LifeLike.createGrid(state));
  },
  /**
   * Controls related to the PhaseDiagram mode
   *  - moving the window into the diagram, zooming in and out
   *  - selecting paramters from the window as the grid parameters for fixed mode
   */
  "move-right"(grid) {
    if (!grid.phaseDiagram) return;
    const [min, max] = grid.phaseDiagram.alpha;
    const change = (max - min) / 8;
    grid.phaseDiagram.alpha = [min + change, max + change];
  },
  "move-left"(grid) {
    if (!grid.phaseDiagram) return;
    const [min, max] = grid.phaseDiagram.alpha;
    const change = (max - min) / 8;
    grid.phaseDiagram.alpha = [min - change, max - change];
  },
  "move-down"(grid) {
    if (!grid.phaseDiagram) return;
    const [min, max] = grid.phaseDiagram.beta;
    const change = (max - min) / 8;
    grid.phaseDiagram.beta = [min + change, max + change];
  },
  "move-up"(grid) {
    if (!grid.phaseDiagram) return;
    const [min, max] = grid.phaseDiagram.beta;
    const change = (max - min) / 8;
    grid.phaseDiagram.beta = [min - change, max - change];
  },
  "zoom-in"(grid) {
    if (!grid.phaseDiagram) return;
    const [minA, maxA] = grid.phaseDiagram.alpha;
    const [minB, maxB] = grid.phaseDiagram.beta;
    const d = (maxB - minB) / 8;
    grid.phaseDiagram.alpha = [minA + d, maxA - d];
    grid.phaseDiagram.beta = [minB + d, maxB - d];
  },
  "zoom-out"(grid) {
    if (!grid.phaseDiagram) return;
    const [minA, maxA] = grid.phaseDiagram.alpha;
    const [minB, maxB] = grid.phaseDiagram.beta;
    const d = (maxB - minB) / 8;
    grid.phaseDiagram.alpha = [minA - d, maxA + d];
    grid.phaseDiagram.beta = [minB - d, maxB + d];
  },
  "goto-start"(grid) {
    grid.phaseDiagram = structuredClone(
      Shapers[grid.activation].diagram,
    );
  },

  /** Grid resolution control i.e. cell count */
  "increase-res"(grid) {
    grid.width = grid.width + 50;
    grid.height = grid.height + 50;
    Controls.reset(grid);
  },
  "decrease-res"(grid) {
    grid.width = grid.width - 50;
    grid.height = grid.height - 50;
    if (grid.width < 3) grid.width = 3;
    if (grid.height < 3) grid.height = 3;
    Controls.reset(grid);
  },
  /**
   * Uses the middle center value of the current phase diagram range to
   * set the alpha / beta values of the simulation
   */
  "select-params"(grid) {
    if (!grid.phaseDiagram) return;
    const [minA, maxA] = grid.phaseDiagram.alpha;
    const [minB, maxB] = grid.phaseDiagram.beta;
    grid.alpha = (minA + maxA) / 2;
    grid.beta = (minB + maxB) / 2;
  },

  /**
   * Activation function controls
   */
  "set-activation"(grid, name: string) {
    if (name in Shapers) {
      grid.activation = name as ShaperName;
    }
  },
  "next-activation"(grid) {
    const names = Object.keys(Shapers) as ShaperName[];
    const i = names.indexOf(grid.activation);
    grid.activation = names[(i + 1) % names.length];
  },
  "prev-activation"(grid) {
    const names = Object.keys(Shapers) as ShaperName[];
    const i = names.indexOf(grid.activation);
    grid.activation = names[(i - 1 + names.length) % names.length];
  },
  "next-theme"(grid) {
    const i = Themes.indexOf(grid.theme);
    grid.theme = Themes[(i + 1) % Themes.length];
    ColorMap.load(grid.theme);
  },
  "prev-theme"(grid) {
    const i = Themes.indexOf(grid.theme);
    grid.theme = Themes[(i - 1 + Themes.length) % Themes.length];
    ColorMap.load(grid.theme);
  },
  "increase-rate"(grid) {
    grid.changeRate += 1;
  },
  "decrease-rate"(grid) {
    if (grid.changeRate > 1) grid.changeRate -= 1;
  },

  /**
   * Consider eventual removal if playing is controlled by component or terminal utility
   * via direct tick calls
   *
   * I'm thinking stdin is an async function that buffers commands. have a tick N function that
   * checks the buffer after each tick. If there is a command, log how many ticks occured and then
   * run the command. if it is a tick command increment remaining ticks. otherwise run it and put
   * tick on the back of the buffer
   */
  "play-pause"(grid) {
    grid.playing = !grid.playing;
  },
  "debug"(grid) {
    console.log(JSON.stringify(grid.phaseDiagram));
  },
} satisfies Record<string, Control>;
type ControlName = keyof typeof Controls;
